#!/usr/bin/env bash

set -uo pipefail

kubectl_grep() {
	local res_name="${1:-}"
	local res_type="${2:-}"

	if [ -z "${res_name}" ]; then
		echo "resource name is missing"
		exit 1
	fi

	for r in $(kubectl api-resources -o name | grep -i "${res_type}" | grep -vE "^events$" )
	do
		res=$(kubectl get "${r}" -A 2>/dev/null | grep -i "${res_name}")
		if ! [ -z "${res}" ]; then
			echo; echo "${r}"
			echo "${res}"
		fi
	done
}

main() {
	kubectl_grep $@
}

main $@
