#!/usr/bin/env bash

set -o pipefail

main() {
        if [ -z "${1}" ]; then
                echo "resource name is missing"
                exit 1
        fi

        for r in $(kubectl api-resources -o name | grep -i "${2}" | grep -vE "^events$" )
        do
                res=$(kubectl get "${r}" -A 2>/dev/null | grep -i "${1}")
                if ! [ -z "${res}" ]; then
                        echo; echo "${r}"
                        echo "${res}"
                fi
        done
}

main $@
